name: Docker Validation Runner

on:
  workflow_dispatch:
    inputs:
      code:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node (stable fix)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t probe-sandbox .

      - name: Run Docker Validation
        run: |
          RESULT=$(docker run --rm probe-sandbox "${{ github.event.inputs.code }}")

          echo "Result: $RESULT"

          curl -X POST https://https://probe-backend-ulu3.onrender.com//store-result \
            -H "Content-Type: application/json" \
            -d "{\"code\":\"${{ github.event.inputs.code}}\",\"result\":\"$RESULT\"}"