- name: Build Docker Image
  run: |
    docker build -t probe-sandbox ./server

- name: Run Docker Validation
  run: |
    RESULT=$(docker run --rm probe-sandbox "${{ github.event.inputs.code }}")

    echo "Result: $RESULT"

    curl -X POST https://https://probe-backend-ulu3.onrender.com//store-result \
      -H "Content-Type: application/json" \
      -d "{\"code\":\"${{ github.event.inputs.code}}\",\"result\":\"$RESULT\"}"
